# Copied from https://github.com/hashicorp/terraform-provider-scaffolding-framework
# with changes:
#   - removed examples "before hooks"
#   - only build for linux-amd64
#   - enable CGO

# Visit https://goreleaser.com for documentation on how to customize this
# behavior.
builds:
- env:
    - CGO_ENABLED=1
    - PKG_CONFIG_SYSROOT_DIR=/sysroot/macos/amd64
    - PKG_CONFIG_PATH=/sysroot/macos/amd64/usr/local/lib/pkgconfig
    - CC=o64-clang
    - CXX=o64-clang++
  binary: golang-cross
  mod_timestamp: '{{ .CommitTimestamp }}'
  flags:
    - -trimpath
  ldflags:
    - '-s -w -X main.version={{.Version}}'
  targets:
    - darwin_amd64
  binary: '{{ .ProjectName }}_v{{ .Version }}'
- env:
    - CGO_ENABLED=1
  mod_timestamp: '{{ .CommitTimestamp }}'
  flags:
    - -trimpath
  ldflags:
    - '-s -w -X main.version={{.Version}}'
  targets:
    - linux_amd64
  binary: '{{ .ProjectName }}_v{{ .Version }}'


archives:
- format: zip
  name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
checksum:
  extra_files:
    - glob: 'terraform-registry-manifest.json'
      name_template: '{{ .ProjectName }}_{{ .Version }}_manifest.json'
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
  algorithm: sha256
signs:
  - artifacts: checksum
    args:
      # if you are using this in a GitHub action or some other automated pipeline, you 
      # need to pass the batch flag to indicate its not interactive.
      - "--batch"
      - "--local-user"
      - "{{ .Env.GPG_FINGERPRINT }}" # set this environment variable for your signing key
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"
release:
  extra_files:
    - glob: 'terraform-registry-manifest.json'
      name_template: '{{ .ProjectName }}_{{ .Version }}_manifest.json'
  # If you want to manually examine the release before its live, uncomment this line:
  # draft: true
changelog:
  skip: true
