# Adapted from https://github.com/hashicorp/terraform-provider-scaffolding-framework
# to work with CGO (inside Docker)

# Visit https://goreleaser.com for documentation on how to customize this
# behavior.
builds:
# darwin builds use osxcross (/usr/local/osxcross)
- id: terraform-provider-ic-darwin_amd64
  env:
    - CC=o64-clang
    - CXX=o64-clang++
  mod_timestamp: '{{ .CommitTimestamp }}'
  flags:
    - -trimpath
  ldflags:
    - '-s -w -X main.version={{.Version}}'
  targets:
    - darwin_amd64
  binary: '{{ .ProjectName }}_v{{ .Version }}'
- id: terraform-provider-ic-darwin_arm64
  env:
    - CC=oa64-clang
    - CXX=oa64-clang++
  mod_timestamp: '{{ .CommitTimestamp }}'
  flags:
    - -trimpath
  ldflags:
    - '-s -w -X main.version={{.Version}}'
  targets:
    - darwin_arm64
  binary: '{{ .ProjectName }}_v{{ .Version }}'

- id: terraform-provider-ic-linux_amd64
  mod_timestamp: '{{ .CommitTimestamp }}'
  flags:
    - -trimpath
  ldflags:
    - '-s -w -X main.version={{.Version}}'
  targets:
    - linux_amd64
  binary: '{{ .ProjectName }}_v{{ .Version }}'


archives:
- format: zip
  name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
checksum:
  extra_files:
    - glob: 'terraform-registry-manifest.json'
      name_template: '{{ .ProjectName }}_{{ .Version }}_manifest.json'
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
  algorithm: sha256
signs:
  - artifacts: checksum
    args:
      # need to pass the batch flag to indicate its not interactive
      - "--batch"

      # the passphrase used in signing
      - "--passphrase"
      - "{{ .Env.PASSPHRASE }}"

      # without this gpg complains about bad ioctl device
      - "--pinentry-mode"
      - "loopback"

      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"
release:
  extra_files:
    - glob: 'terraform-registry-manifest.json'
      name_template: '{{ .ProjectName }}_{{ .Version }}_manifest.json'
changelog:
  disable: true
